### ISSUE TITLE
Can't Run Robot Code

### ISSUE THREAD

**Issue by maniyar1** [dominikWin/badlog#5]
We're trying to deploy badlog onto our bot but we're getting a ClassNotFoundException. We can't access the CD paper anymore because of the changed site. Are we supposed to upload a jar or something?

**Comment by dominikWin** [comment]
Do you have the json-simple library added? That’s what usually causes that error. Are you installing through Gradle or manual?

**Comment by maniyar1** [comment]
Through Gradle

**Comment by dominikWin** [comment]
That’s weird, is it grabbing the json library? Anything else in the errors?

**Comment by maniyar1** [comment]
No? That's just on the bot, it works fine on our computer(s). The full exception is ```ERROR 1 Unhandled exception instantiating robot jdk.internal.loader.BuiltinClassLoaderjava.lang.ClassNotFoundException:badlog.lib.BadLog```

**Comment by maniyar1** [comment]
I can try the JSON lib, is there a way to get the latest commit jar without compiling?

**Comment by dominikWin** [comment]
If you are using grade you can put the master hash instead of the version tag. Otherwise its proabably the build system not pushing code properly. I think [this](
https://www.chiefdelphi.com/t/creating-a-custom-library-for-robot-code-in-eclipse/140342/4) might be how this gets fixed. A lot changed with GradleRio so I’m not sure. I’ll look into this some more

**Comment by dominikWin** [comment]
Another option is also a manual install, which might work

**Comment by maniyar1** [comment]
Yeah, is this working for you? For now we'll try the manual install. If that doesn't work we'll just copy the code directly in our repo for now.

**Comment by dominikWin** [comment]
I'll check if it still works at our meeting tonight.

By the way I fixed the paper link. It doesn't contain anything about this issue though

**Comment by maniyar1** [comment]
Ok, awesome, thanks. I'm not exactly sure how to access the jar files, so I'm just going to copy the code over for now (and since ideally we want gradle anyway), and we'll switch it back if/once it gets fixed. Thanks for the quick responses.

**Comment by maniyar1** [comment]
Weird, it's like I can't get anything from Gradle, it's not just that, I can't use the JSONSimple either, so I think you might be good on your end.

**Comment by maniyar1** [comment]
Oh, got it. I think somewhere I read to use implement () instead of compile because my compile wasn't working and that was the problem. So don't use implement for anything in Gradle for Robot. Thanks for the help.

**Comment by dominikWin** [comment]
No problem, by the way the jars are all [here](https://github.com/dominikWin/badlog/releases). For some reason though Github thinks 0.1.0 came after 0.1.1
